#ifndef SYNAPSE_RUNTIME_UTILS_CONSTANTS_HPP_
#define SYNAPSE_RUNTIME_UTILS_CONSTANTS_HPP_

#define DEVICE_ID 0
#define ELECTION_ID_LOW 1
#define ELECTION_ID_HIGH 0

#endif // SYNAPSE_RUNTIME_UTILS_CONSTANTS_HPP_