#ifndef SYNAPSE_RUNTIME_P4RUNTIME_CONSTANTS_HPP_
#define SYNAPSE_RUNTIME_P4RUNTIME_CONSTANTS_HPP_

#define SYNAPSE_DEVICE_ID 0
#define SYNAPSE_ELECTION_ID_LOW 1
#define SYNAPSE_ELECTION_ID_HIGH 0

#endif // SYNAPSE_RUNTIME_P4RUNTIME_CONSTANTS_HPP_